name: Style Check

on: [push, pull_request]

jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: TrueBrain/actions-flake8@master
    mypy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: jpetrucciani/mypy-check@master
